- id: svglint
  name: svglint
  entry: svglint -C  # The `-C` flag is used due to https://github.com/simple-icons/svglint/issues/56
  description: Linter for SVGs
  language: node
  types:
    - svg
  minimum_pre_commit_version: 1.5.0
