name: Test
on: [push, pull_request]

permissions: read-all

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Node.js setup
        uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
  test:
    name: Run tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        node-version:
          - 12.20.0
          - 14.13.1
          - 16.0.0
          - 12
          - 14
          - 16
          - 17
        include:
          - os: macos-latest
            node-version: 16
          - os: windows-latest
            node-version: 16
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Node.js setup
        uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm test
