name: Test
on: [push, pull_request]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [12, 14, 16]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Node.js setup
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm test
